/**
 * Waitlisted API
 * Waitlisted API
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['waitlisted-js/ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Waitlisted) {
      root.Waitlisted = {};
    }
    root.Waitlisted.SiteResponse = factory(root.Waitlisted.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SiteResponse model module.
   * @module waitlisted-js/waitlisted-js-models/SiteResponse
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>SiteResponse</code>.
   * @alias module:waitlisted-js/waitlisted-js-models/SiteResponse
   * @class
   */
  var exports = function() {
    var _this = this;






























  };

  /**
   * Constructs a <code>SiteResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:waitlisted-js/waitlisted-js-models/SiteResponse} obj Optional instance to populate.
   * @return {module:waitlisted-js/waitlisted-js-models/SiteResponse} The populated <code>SiteResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('brand_color')) {
        obj['brand_color'] = ApiClient.convertToType(data['brand_color'], 'String');
      }
      if (data.hasOwnProperty('button_text_color')) {
        obj['button_text_color'] = ApiClient.convertToType(data['button_text_color'], 'String');
      }
      if (data.hasOwnProperty('custom_styles')) {
        obj['custom_styles'] = ApiClient.convertToType(data['custom_styles'], 'String');
      }
      if (data.hasOwnProperty('ask_name')) {
        obj['ask_name'] = ApiClient.convertToType(data['ask_name'], 'Boolean');
      }
      if (data.hasOwnProperty('signup_title')) {
        obj['signup_title'] = ApiClient.convertToType(data['signup_title'], 'String');
      }
      if (data.hasOwnProperty('signup_copy')) {
        obj['signup_copy'] = ApiClient.convertToType(data['signup_copy'], 'String');
      }
      if (data.hasOwnProperty('position_title')) {
        obj['position_title'] = ApiClient.convertToType(data['position_title'], 'String');
      }
      if (data.hasOwnProperty('social_copy')) {
        obj['social_copy'] = ApiClient.convertToType(data['social_copy'], 'String');
      }
      if (data.hasOwnProperty('social_message')) {
        obj['social_message'] = ApiClient.convertToType(data['social_message'], 'String');
      }
      if (data.hasOwnProperty('domain')) {
        obj['domain'] = ApiClient.convertToType(data['domain'], 'String');
      }
      if (data.hasOwnProperty('share_social_copy')) {
        obj['share_social_copy'] = ApiClient.convertToType(data['share_social_copy'], 'String');
      }
      if (data.hasOwnProperty('referral_copy')) {
        obj['referral_copy'] = ApiClient.convertToType(data['referral_copy'], 'String');
      }
      if (data.hasOwnProperty('check_position_copy')) {
        obj['check_position_copy'] = ApiClient.convertToType(data['check_position_copy'], 'String');
      }
      if (data.hasOwnProperty('join_button_copy')) {
        obj['join_button_copy'] = ApiClient.convertToType(data['join_button_copy'], 'String');
      }
      if (data.hasOwnProperty('check_reservation_copy')) {
        obj['check_reservation_copy'] = ApiClient.convertToType(data['check_reservation_copy'], 'String');
      }
      if (data.hasOwnProperty('email_field_label')) {
        obj['email_field_label'] = ApiClient.convertToType(data['email_field_label'], 'String');
      }
      if (data.hasOwnProperty('name_field_label')) {
        obj['name_field_label'] = ApiClient.convertToType(data['name_field_label'], 'String');
      }
      if (data.hasOwnProperty('thank_you_share_template')) {
        obj['thank_you_share_template'] = ApiClient.convertToType(data['thank_you_share_template'], 'String');
      }
      if (data.hasOwnProperty('waitlist_threshold')) {
        obj['waitlist_threshold'] = ApiClient.convertToType(data['waitlist_threshold'], 'Integer');
      }
      if (data.hasOwnProperty('use_custom_thank_you')) {
        obj['use_custom_thank_you'] = ApiClient.convertToType(data['use_custom_thank_you'], 'Boolean');
      }
      if (data.hasOwnProperty('hide_waitlist')) {
        obj['hide_waitlist'] = ApiClient.convertToType(data['hide_waitlist'], 'Boolean');
      }
      if (data.hasOwnProperty('unmet_shared_template')) {
        obj['unmet_shared_template'] = ApiClient.convertToType(data['unmet_shared_template'], 'String');
      }
      if (data.hasOwnProperty('threshold_met')) {
        obj['threshold_met'] = ApiClient.convertToType(data['threshold_met'], 'Boolean');
      }
      if (data.hasOwnProperty('website_url')) {
        obj['website_url'] = ApiClient.convertToType(data['website_url'], 'String');
      }
      if (data.hasOwnProperty('tracking_code')) {
        obj['tracking_code'] = ApiClient.convertToType(data['tracking_code'], 'String');
      }
      if (data.hasOwnProperty('custom_css')) {
        obj['custom_css'] = ApiClient.convertToType(data['custom_css'], 'String');
      }
      if (data.hasOwnProperty('hide_branding')) {
        obj['hide_branding'] = ApiClient.convertToType(data['hide_branding'], 'Boolean');
      }
      if (data.hasOwnProperty('total_count')) {
        obj['total_count'] = ApiClient.convertToType(data['total_count'], 'Integer');
      }
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} brand_color
   */
  exports.prototype['brand_color'] = undefined;
  /**
   * @member {String} button_text_color
   */
  exports.prototype['button_text_color'] = undefined;
  /**
   * @member {String} custom_styles
   */
  exports.prototype['custom_styles'] = undefined;
  /**
   * @member {Boolean} ask_name
   */
  exports.prototype['ask_name'] = undefined;
  /**
   * @member {String} signup_title
   */
  exports.prototype['signup_title'] = undefined;
  /**
   * @member {String} signup_copy
   */
  exports.prototype['signup_copy'] = undefined;
  /**
   * @member {String} position_title
   */
  exports.prototype['position_title'] = undefined;
  /**
   * @member {String} social_copy
   */
  exports.prototype['social_copy'] = undefined;
  /**
   * @member {String} social_message
   */
  exports.prototype['social_message'] = undefined;
  /**
   * @member {String} domain
   */
  exports.prototype['domain'] = undefined;
  /**
   * @member {String} share_social_copy
   */
  exports.prototype['share_social_copy'] = undefined;
  /**
   * @member {String} referral_copy
   */
  exports.prototype['referral_copy'] = undefined;
  /**
   * @member {String} check_position_copy
   */
  exports.prototype['check_position_copy'] = undefined;
  /**
   * @member {String} join_button_copy
   */
  exports.prototype['join_button_copy'] = undefined;
  /**
   * @member {String} check_reservation_copy
   */
  exports.prototype['check_reservation_copy'] = undefined;
  /**
   * @member {String} email_field_label
   */
  exports.prototype['email_field_label'] = undefined;
  /**
   * @member {String} name_field_label
   */
  exports.prototype['name_field_label'] = undefined;
  /**
   * @member {String} thank_you_share_template
   */
  exports.prototype['thank_you_share_template'] = undefined;
  /**
   * @member {Integer} waitlist_threshold
   */
  exports.prototype['waitlist_threshold'] = undefined;
  /**
   * @member {Boolean} use_custom_thank_you
   */
  exports.prototype['use_custom_thank_you'] = undefined;
  /**
   * @member {Boolean} hide_waitlist
   */
  exports.prototype['hide_waitlist'] = undefined;
  /**
   * @member {String} unmet_shared_template
   */
  exports.prototype['unmet_shared_template'] = undefined;
  /**
   * @member {Boolean} threshold_met
   */
  exports.prototype['threshold_met'] = undefined;
  /**
   * @member {String} website_url
   */
  exports.prototype['website_url'] = undefined;
  /**
   * @member {String} tracking_code
   */
  exports.prototype['tracking_code'] = undefined;
  /**
   * @member {String} custom_css
   */
  exports.prototype['custom_css'] = undefined;
  /**
   * @member {Boolean} hide_branding
   */
  exports.prototype['hide_branding'] = undefined;
  /**
   * @member {Integer} total_count
   */
  exports.prototype['total_count'] = undefined;



  return exports;
}));


