/**
 * Waitlisted API
 * Waitlisted API
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['waitlisted-js/ApiClient', 'waitlisted-js/waitlisted-js-models/ErrorResponse', 'waitlisted-js/waitlisted-js-models/FormResponse', 'waitlisted-js/waitlisted-js-models/Reservation', 'waitlisted-js/waitlisted-js-models/ReservationRequest', 'waitlisted-js/waitlisted-js-models/ReservationsResponse', 'waitlisted-js/waitlisted-js-models/SiteResponse', 'waitlisted-js/waitlisted-js-api/ReservationApi', 'waitlisted-js/waitlisted-js-api/SiteApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./waitlisted-js-models/ErrorResponse'), require('./waitlisted-js-models/FormResponse'), require('./waitlisted-js-models/Reservation'), require('./waitlisted-js-models/ReservationRequest'), require('./waitlisted-js-models/ReservationsResponse'), require('./waitlisted-js-models/SiteResponse'), require('./waitlisted-js-api/ReservationApi'), require('./waitlisted-js-api/SiteApi'));
  }
}(function(ApiClient, ErrorResponse, FormResponse, Reservation, ReservationRequest, ReservationsResponse, SiteResponse, ReservationApi, SiteApi) {
  'use strict';

  /**
   * Client library for Waitlisted.co.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var Waitlisted = require('waitlisted-js/index'); // See note below*.
   * var xxxSvc = new Waitlisted.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new Waitlisted.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['waitlisted-js/index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new Waitlisted.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new Waitlisted.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module waitlisted-js/index
   * @version 2.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:waitlisted-js/ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The ErrorResponse model constructor.
     * @property {module:waitlisted-js/waitlisted-js-models/ErrorResponse}
     */
    ErrorResponse: ErrorResponse,
    /**
     * The FormResponse model constructor.
     * @property {module:waitlisted-js/waitlisted-js-models/FormResponse}
     */
    FormResponse: FormResponse,
    /**
     * The Reservation model constructor.
     * @property {module:waitlisted-js/waitlisted-js-models/Reservation}
     */
    Reservation: Reservation,
    /**
     * The ReservationRequest model constructor.
     * @property {module:waitlisted-js/waitlisted-js-models/ReservationRequest}
     */
    ReservationRequest: ReservationRequest,
    /**
     * The ReservationsResponse model constructor.
     * @property {module:waitlisted-js/waitlisted-js-models/ReservationsResponse}
     */
    ReservationsResponse: ReservationsResponse,
    /**
     * The SiteResponse model constructor.
     * @property {module:waitlisted-js/waitlisted-js-models/SiteResponse}
     */
    SiteResponse: SiteResponse,
    /**
     * The ReservationApi service constructor.
     * @property {module:waitlisted-js/waitlisted-js-api/ReservationApi}
     */
    ReservationApi: ReservationApi,
    /**
     * The SiteApi service constructor.
     * @property {module:waitlisted-js/waitlisted-js-api/SiteApi}
     */
    SiteApi: SiteApi
  };

  return exports;
}));
