/**
 * Waitlisted API
 * Waitlisted API
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['waitlisted-js/ApiClient', 'waitlisted-js/waitlisted-js-models/SiteResponse', 'waitlisted-js/waitlisted-js-models/ErrorResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../waitlisted-js-models/SiteResponse'), require('../waitlisted-js-models/ErrorResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.Waitlisted) {
      root.Waitlisted = {};
    }
    root.Waitlisted.SiteApi = factory(root.Waitlisted.ApiClient, root.Waitlisted.SiteResponse, root.Waitlisted.ErrorResponse);
  }
}(this, function(ApiClient, SiteResponse, ErrorResponse) {
  'use strict';

  /**
   * Site service.
   * @module waitlisted-js/waitlisted-js-api/SiteApi
   * @version 2.0.0
   */

  /**
   * Constructs a new SiteApi. 
   * @alias module:waitlisted-js/waitlisted-js-api/SiteApi
   * @class
   * @param {module:waitlisted-js/ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:waitlisted-js/ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Get site settings and reservation count.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:waitlisted-js/waitlisted-js-models/SiteResponse}
     */
    this.getSite = function() {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = SiteResponse;

      return this.apiClient.callApi(
        '/site', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }
  };

  return exports;
}));
